name: angular_gallery
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  angulardart: ^8.0.0
  angulardart_components: ^1.0.0
  angulardart_forms: ^5.0.0
  angulardart_router: ^2.0.0
  build: '>=0.11.1 <2.0.0'
  build_config: '>=0.2.6 <0.5.0'
  mustache: ^1.0.0

dependency_overrides:
  angulardart_components:
    path: ../angular_components
