import 'dart:async';
import 'dart:io';

import 'package:path/path.dart' as path;

import 'command.dart';

/// Generates .template.dart stub files for AOT/native compilation.
///
/// These stubs are required because Dart resolves `package:X/y.template.dart`
/// imports to lib/y.template.dart, not to .dart_tool/build/generated/.
class GenerateStubsCommand extends NgDartCommand {
  @override
  String get name => 'generate-stubs';

  @override
  String get description => 'Generate .template.dart stub files for AOT compilation.';

  @override
  String get invocation => 'ngdart generate-stubs';

  GenerateStubsCommand();

  /// Extracts the package name from pubspec.yaml in the given directory.
  String? _readPackageName(String projectDir) {
    final pubspecFile = File(path.join(projectDir, 'pubspec.yaml'));
    if (!pubspecFile.existsSync()) return null;

    final content = pubspecFile.readAsStringSync();
    for (final line in content.split('\n')) {
      final trimmed = line.trim();
      if (trimmed.startsWith('name:')) {
        final nameValue = trimmed.substring(trimmed.indexOf(':') + 1).trim();
        // Skip empty or whitespace-only names
        if (nameValue.isNotEmpty && RegExp(r'^[a-zA-Z_]').hasMatch(nameValue)) {
          return nameValue;
        }
      }
    }
    return null;
  }

  @override
  Future<void> runCommand() async {
    // Find the nearest project directory (contains pubspec.yaml)
    var projectDir = Directory.current.path;
    var candidate = Directory.current.path;
    for (var depth = 0; depth < 15; depth++) {
      if (File(path.join(candidate, 'pubspec.yaml')).existsSync()) {
        projectDir = candidate;
        break;
      }
      final parent = path.dirname(candidate);
      if (parent == candidate) break;
      candidate = parent;
    }

    // Read the project's package name to filter template copying
    final packageName = _readPackageName(projectDir);

    int created = 0;
    int unchanged = 0;
    int updated = 0;

    // Create web/main.template.dart stub if it doesn't exist (SSR projects)
    final webMainTemplate = File(path.join(projectDir, 'web', 'main.template.dart'));
    if (!webMainTemplate.existsSync()) {
      await webMainTemplate.writeAsString('''/// Stub template for web/main.dart - native/AOT compatible.
/// AUTO-GENERATED by `ngdart generate-stubs` — DO NOT EDIT MANUALLY.
library;

import 'package:angulardart/angulardart.dart';

// Placeholder for generated factory — will be replaced by build_runner
class AppComponentNgFactory {
  static ComponentFactory<Object> get factory => throw UnimplementedError();
}
''');
    }

    // Create stubs for lib/ component templates only if the corresponding .dart source exists.
    // This prevents creating hybrid-component stubs in pure SSR projects.
    final libTemplates = <String, String>{
      'home_component.template.dart': '''/// Stub template for home_component - native/AOT compatible.
/// AUTO-GENERATED by `ngdart generate-stubs` — DO NOT EDIT MANUALLY.
library;

import 'package:angulardart/angulardart.dart';

class HomeComponentNgFactory {
  static ComponentFactory<Object> get factory => throw UnimplementedError();
}
''',
      'about_component.template.dart': '''/// Stub template for about_component - native/AOT compatible.
/// AUTO-GENERATED by `ngdart generate-stubs` — DO NOT EDIT MANUALLY.
library;

import 'package:angulardart/angulardart.dart';

class AboutComponentNgFactory {
  static ComponentFactory<Object> get factory => throw UnimplementedError();
}
''',
      'dashboard_component.template.dart': '''/// Stub template for dashboard_component - native/AOT compatible.
/// AUTO-GENERATED by `ngdart generate-stubs` — DO NOT EDIT MANUALLY.
library;

import 'package:angulardart/angulardart.dart';

class DashboardComponentNgFactory {
  static ComponentFactory<Object> get factory => throw UnimplementedError();
}
''',
    };

    for (final entry in libTemplates.entries) {
      final componentName = entry.key.replaceAll('.template.dart', '');
      final componentSource = File(path.join(projectDir, 'lib', componentName));
      // Only create stub if the corresponding .dart source file exists
      if (!componentSource.existsSync()) continue;

      final templateFile = File(path.join(projectDir, 'lib', entry.key));
      if (!templateFile.existsSync()) {
        await templateFile.writeAsString(entry.value);
        created++;
        print('Created: lib/${entry.key}');
      } else {
        unchanged++;
      }
    }

    // Copy generated .template.dart files from build_runner output to project directories.
    // Only copy templates from the project's own package, not from dependencies.
    int copiedCount = 0;
    final dartToolBuild = Directory(path.join(projectDir, '.dart_tool', 'build', 'generated'));
    if (dartToolBuild.existsSync() && packageName != null) {
      final projectGeneratedDir = Directory(path.join(dartToolBuild.path, packageName));
      if (projectGeneratedDir.existsSync()) {
        final generatedLib = path.join(projectGeneratedDir.path, 'lib');
        final generatedWeb = path.join(projectGeneratedDir.path, 'web');

        // Copy lib/ templates to project's lib/
        if (Directory(generatedLib).existsSync()) {
          copiedCount += await _copyTemplatesRecursive(
            Directory(generatedLib),
            path.join(projectDir, 'lib'),
          );
        }

        // Copy web/ templates to project's web/
        if (Directory(generatedWeb).existsSync()) {
          copiedCount += await _copyTemplatesRecursive(
            Directory(generatedWeb),
            path.join(projectDir, 'web'),
          );
        }
      } else {
        print('Warning: No generated output found for package "$packageName" in .dart_tool/build/generated/');
      }
    }

    // Update the created counter with the number of files copied by _copyTemplatesRecursive.
    // These are new files that were written to disk (not existing files that were skipped).
    created += copiedCount;

    // Post-process: remove browser-only .template.dart files and fix imports.
    // This is necessary because the Angular compiler generates direct imports
    // to _browser.template.dart files without respecting conditional exports.
    final libDir = Directory(path.join(projectDir, 'lib'));
    if (libDir.existsSync()) {
      await _postProcessTemplatesForSsr(libDir);

      // Also ensure platform_dom.template.dart has a safe stub for SSR projects.
      // This is a safety net in case the post-processing didn't fully clean it up.
      final projectPlatformDomTemplate = File(path.join(projectDir, 'lib', 'platform_dom.template.dart'));
      if (projectPlatformDomTemplate.existsSync()) {
        final content = await projectPlatformDomTemplate.readAsString();
        // Only overwrite if the file still has browser imports or is empty/minimal
        if (content.contains('_browser') || !content.contains('initReflector')) {
          await projectPlatformDomTemplate.writeAsString('''/// Safe stub template for platform_dom - native/AOT compatible.
/// AUTO-GENERATED by `ngdart generate-stubs` — DO NOT EDIT MANUALLY.
library;

void initReflector() {}
''');
          updated++;
          print('Updated: lib/platform_dom.template.dart (safe stub)');
        }
      }
    }

    print('');
    print('Stubs: $created created, $updated updated, $unchanged unchanged');
  }

  /// Post-process .template.dart files to remove browser-only imports.
  ///
  /// The Angular compiler generates direct imports like:
  ///   import 'platform_dom_browser.template.dart' as _ref0;
  /// This causes compilation failures on the VM because platform_dom_browser.dart
  /// exports package:web which uses dart:js_interop types not available on native.
  Future<void> _postProcessTemplatesForSsr(Directory dir) async {
    // Pattern to match full import lines of *_browser.template.dart files (including 'as' alias)
    final browserImportPattern = RegExp(r'import\s+[^\n;]*_browser\.template\.dart[^\n;]*');

    for (final entity in dir.listSync(recursive: true)) {
      if (entity is File && entity.path.endsWith('.template.dart')) {
        final content = await entity.readAsString();
        final matches = browserImportPattern.allMatches(content).toList();

        if (matches.isNotEmpty) {
          // Remove all _browser.template.dart imports and their initReflector() calls
          var newContent = content;

          // Collect aliases to remove from the file
          final aliasesToRemove = <String>{};

          for (final match in matches) {
            final matchedText = match.group(0)!;

            // Extract the alias (_ref0, _ref1, etc.) if present - look for 'as XXX' pattern
            final aliasMatch = RegExp(r'\bas\s+(\w+)').firstMatch(matchedText);

            if (aliasMatch != null) {
              aliasesToRemove.add(aliasMatch.group(1)!);
            }

            // Find the full line to remove (including newline)
            final lineStart = content.substring(0, match.start).lastIndexOf('\n') + 1;
            final lineEnd = content.indexOf('\n', match.end);
            final endPos = lineEnd > 0 ? lineEnd : content.length;

            // Remove the entire line (from start of line to next newline)
            newContent = newContent.replaceRange(lineStart, endPos, '');
          }

          // Also remove any _refN.initReflector() calls for removed aliases
          for (final alias in aliasesToRemove) {
            final initReflectorPattern = RegExp(
              r'\s*' + RegExp.escape(alias) + r'\.initReflector\(\);',
            );
            newContent = newContent.replaceAll(initReflectorPattern, '');

            // Also remove the blank line before it if present
            newContent = newContent.replaceAll(
              '\n\n$alias.initReflector();',
              '\n',
            );
          }

          // Clean up extra blank lines (3+ consecutive newlines -> 2)
          newContent = newContent.replaceAll(RegExp(r'\n{3,}'), '\n\n');

          await entity.writeAsString(newContent);
          print('Fixed: ${path.relative(entity.path, from: Directory.current.path)}');
        }
      } else if (entity is File && entity.path.contains('_browser.template.dart')) {
        // Delete _browser.template.dart files - they're not needed on the VM
        await entity.delete();
        print('Deleted browser template: ${path.relative(entity.path, from: Directory.current.path)}');
      } else if (entity is Directory) {
        // Recurse into subdirectories
        await _postProcessTemplatesForSsr(entity);
      }
    }
  }

  Future<int> _copyTemplatesRecursive(Directory sourceDir, String targetDir) async {
    int count = 0;
    await Directory(targetDir).create(recursive: true);

    for (final entity in sourceDir.listSync()) {
      if (entity is File) {
        final fileName = path.basename(entity.path);
        if (!fileName.endsWith('.template.dart') && !fileName.endsWith('.css.shim.dart')) continue;

        final targetFile = File(path.join(targetDir, fileName));
        final content = await entity.readAsString();

        if (!targetFile.existsSync() || targetFile.readAsBytesSync().length != content.length) {
          await targetFile.writeAsString(content);
          print('Copied: ${path.relative(targetFile.path, from: Directory.current.path)}');
          count++;
        }
      } else if (entity is Directory) {
        final subDirName = path.basename(entity.path);
        count += await _copyTemplatesRecursive(entity, path.join(targetDir, subDirName));
      }
    }

    return count;
  }
}


