import 'dart:async';
import 'dart:io';

import 'package:path/path.dart' as path;

import 'command.dart';

/// Generates .template.dart stub files for AOT/native compilation.
///
/// These stubs are required because Dart resolves `package:X/y.template.dart`
/// imports to lib/y.template.dart, not to .dart_tool/build/generated/.
class GenerateStubsCommand extends NgDartCommand {
  @override
  String get name => 'generate-stubs';

  @override
  String get description => 'Generate .template.dart stub files for AOT compilation.';

  @override
  String get invocation => 'ngdart generate-stubs';

  GenerateStubsCommand();

  /// Find the monorepo root by walking up from cwd looking for known markers.
  String _findRepoRoot() {
    var candidate = Directory.current.path;
    final markers = ['angulardart_server', path.join('angular', 'angular')];

    for (var depth = 0; depth < 15; depth++) {
      for (final marker in markers) {
        if (Directory(path.join(candidate, marker)).existsSync()) {
          return candidate;
        }
      }
      final parent = path.dirname(candidate);
      if (parent == candidate) break; // Reached filesystem root
      candidate = parent;
    }

    throw StateError(
      'Could not find monorepo root. Run this command from within the repository.',
    );
  }

  @override
  Future<void> runCommand() async {
    // Find the nearest project directory (contains pubspec.yaml)
    var projectDir = Directory.current.path;
    var candidate = Directory.current.path;
    for (var depth = 0; depth < 15; depth++) {
      if (File(path.join(candidate, 'pubspec.yaml')).existsSync()) {
        projectDir = candidate;
        break;
      }
      final parent = path.dirname(candidate);
      if (parent == candidate) break;
      candidate = parent;
    }

    // Try to find monorepo root for package stubs, but don't fail if not found
    String? repoRoot;
    try {
      repoRoot = _findRepoRoot();
    } catch (_) {}

    final stubs = <Stub>[
      Stub(
        packageName: 'platform_dom',
        relativePath: path.join('angular', 'examples', 'hello_world_ssr', 'lib', 'platform_dom.template.dart'),
        content: '''/// Stub template for platform_dom - native/AOT compatible.
/// AUTO-GENERATED by `ngdart generate-stubs` — DO NOT EDIT MANUALLY.
library;

void initReflector() {}
''',
      ),
    ];

    // Create web/main.template.dart stub if it doesn't exist (SSR projects)
    final webMainTemplate = File(path.join(projectDir, 'web', 'main.template.dart'));
    if (!webMainTemplate.existsSync()) {
      await webMainTemplate.writeAsString('''/// Stub template for web/main.dart - native/AOT compatible.
/// AUTO-GENERATED by `ngdart generate-stubs` — DO NOT EDIT MANUALLY.
library;

import 'package:angulardart/angulardart.dart';

// Placeholder for generated factory — will be replaced by build_runner
class AppComponentNgFactory {
  static ComponentFactory<Object> get factory => throw UnimplementedError();
}
''');
    }

    int created = 0;
    int unchanged = 0;
    int updated = 0;

    for (final stub in stubs) {
      final filePath = repoRoot != null ? path.join(repoRoot, stub.relativePath) : path.join(projectDir, stub.relativePath);
      final file = File(filePath);

      if (file.existsSync()) {
        final existing = await file.readAsString();
        if (existing == stub.content) {
          unchanged++;
          continue;
        }
        await file.writeAsString(stub.content);
        updated++;
        print('Updated: ${stub.relativePath}');
      } else {
        await file.create(recursive: true);
        await file.writeAsString(stub.content);
        created++;
        print('Created: ${stub.relativePath}');
      }
    }

    print('');
    print('Stubs: $created created, $updated updated, $unchanged unchanged');
  }
}

class Stub {
  final String packageName;
  final String relativePath;
  final String content;

  const Stub({
    required this.packageName,
    required this.relativePath,
    required this.content,
  });
}
