import 'dart:async';
import 'dart:io';

import 'package:path/path.dart' as path;

import 'command.dart';

/// Generates .template.dart stub files for AOT/native compilation.
///
/// These stubs are required because Dart resolves `package:X/y.template.dart`
/// imports to lib/y.template.dart, not to .dart_tool/build/generated/.
class GenerateStubsCommand extends NgDartCommand {
  @override
  String get name => 'generate-stubs';

  @override
  String get description => 'Generate .template.dart stub files for AOT compilation.';

  @override
  String get invocation => 'ngdart generate-stubs';

  GenerateStubsCommand();

  /// Find the monorepo root by walking up from cwd looking for known markers.
  String _findRepoRoot() {
    var candidate = Directory.current.path;
    final markers = ['angulardart_server', path.join('angular', 'angular')];

    for (var depth = 0; depth < 15; depth++) {
      for (final marker in markers) {
        if (Directory(path.join(candidate, marker)).existsSync()) {
          return candidate;
        }
      }
      final parent = path.dirname(candidate);
      if (parent == candidate) break; // Reached filesystem root
      candidate = parent;
    }

    throw StateError(
      'Could not find monorepo root. Run this command from within the repository.',
    );
  }

  @override
  Future<void> runCommand() async {
    final repoRoot = _findRepoRoot();

    final stubs = <Stub>[
      Stub(
        packageName: 'angulardart',
        relativePath: path.join('angular', 'angular', 'lib', 'angulardart.template.dart'),
        content: '''/// Stub template for angulardart - native/AOT compatible.
///
/// AUTO-GENERATED by `ngdart generate-stubs` — DO NOT EDIT MANUALLY.
/// This file is a stub that allows AOT compilation on native platforms.
/// The actual template is generated by build_runner for web builds.
library;

void initReflector() {
  // No-op on native/AOT - reflection not needed for server rendering
}
''',
      ),
      Stub(
        packageName: 'angulardart_server',
        relativePath: path.join('angulardart_server', 'lib', 'angulardart_server.template.dart'),
        content: '''/// Stub template for angulardart_server - native/AOT compatible.
///
/// AUTO-GENERATED by `ngdart generate-stubs` — DO NOT EDIT MANUALLY.
/// This file is a stub that allows AOT compilation on native platforms.
/// The actual template is generated by build_runner for web builds.
library;

void initReflector() {
  // No-op on native/AOT - reflection not needed for server rendering
}
''',
      ),
      Stub(
        packageName: 'platform_dom',
        relativePath: path.join('angular', 'examples', 'hello_world_ssr', 'lib', 'platform_dom.template.dart'),
        content: '''/// Stub template for platform_dom - native/AOT compatible.
/// AUTO-GENERATED by `ngdart generate-stubs` — DO NOT EDIT MANUALLY.
library;

void initReflector() {}
''',
      ),
    ];

    int created = 0;
    int unchanged = 0;
    int updated = 0;

    for (final stub in stubs) {
      final filePath = path.join(repoRoot, stub.relativePath);
      final file = File(filePath);

      if (file.existsSync()) {
        final existing = await file.readAsString();
        if (existing == stub.content) {
          unchanged++;
          continue;
        }
        await file.writeAsString(stub.content);
        updated++;
        print('Updated: ${stub.relativePath}');
      } else {
        await file.create(recursive: true);
        await file.writeAsString(stub.content);
        created++;
        print('Created: ${stub.relativePath}');
      }
    }

    print('');
    print('Stubs: $created created, $updated updated, $unchanged unchanged');
  }
}

class Stub {
  final String packageName;
  final String relativePath;
  final String content;

  const Stub({
    required this.packageName,
    required this.relativePath,
    required this.content,
  });
}
