include: ../analysis_options.yaml

analyzer:
  exclude:
    - "**/*.template.dart"
  errors:
    # False positives related to missing .template.dart files
    invalid_assignment: ignore
    argument_type_not_assignable: ignore
