name: angulardart_forms
repository: https://github.com/flutterdocteur/angulardart/tree/main/angular/angular_forms
issue_tracker: https://github.com/flutterdocteur/angulardart/issues
homepage: https://angulardartreborn.com
documentation: https://angulardartreborn.com/guide
description: Forms framework for AngularDart.
version: 6.1.0
topics:
  - angular
  - forms
  - web
  - validation
screenshots:
  - description: 'AngularDart Forms logo'
    path: logo.png
environment:
  sdk: '>=3.0.0 <4.0.0'
platforms:
  web:
dependencies:
  angulardart: '>=9.0.0 <10.0.0'
  meta: '>=1.15.0 <2.0.0'
  web: '>=1.0.0 <2.0.0'
dev_dependencies:
  angulardart_test: '>=6.0.0 <7.0.0'
  build_runner: '>=2.16.0 <3.0.0'
  build_test: '>=3.0.0 <4.0.0'
  build_web_compilers: '>=4.8.0 <5.0.0'
  mockito: '>=5.4.0 <6.0.0'
  lints: '>=6.0.0 <7.0.0'
  test: '>=1.31.0 <2.0.0'
