name: angulardart_router
repository: https://github.com/flutterdocteur/angulardart/tree/main/angular/angular_router
issue_tracker: https://github.com/flutterdocteur/angulardart/issues
homepage: https://github.com/flutterdocteur/angulardart
description: Router for AngularDart.
version: 4.0.3
topics:
  - angular
  - router
  - navigation
  - web

environment:
  sdk: '>=3.0.0 <4.0.0'

platforms:
  web:

dependencies:
  angulardart: ^8.0.0
  collection: ^1.18.0
  web: ^0.5.0
  meta: ^1.15.0

dev_dependencies:
  async: ^2.11.0
  angulardart_test: ^5.0.0
  build_runner: ^2.4.0
  build_test: ^2.2.3
  build_web_compilers: ^4.0.0
  mockito: ^5.4.0
  lints: ^4.0.0
  test: ^1.25.0
