include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/*.template.dart"
  errors:
    dead_code: warning
    todo: ignore
    unused_element: warning
    unused_import: warning
    unused_local_variable: warning
    uri_has_not_been_generated: ignore
    deprecated_member_use_from_same_package: ignore
    deprecated_member_use: ignore

linter:
  rules:
  - prefer_generic_function_type_aliases
