/// Stub library for browser-only modules when running on native/AOT platforms (VM).
///
/// This file is loaded by conditional imports generated by the AngularDart compiler
/// for browser-only modules like `dart:js_interop`, `package:web/*`, and package
/// `.template.dart` files. All symbols are no-op stubs so that generated code can
/// compile and run on the VM without errors during server-side rendering.
library;

// Stub for dart:js_interop's JSObject (used by extension types from package:web).
class JSObject {}

// Stub for .template.dart files - provides empty initReflector() so that calls
// like `_ref1.initReflector()` become no-ops on VM.
void initReflector() {}
