name: material_icon_example
publish_to: none

environment:
  sdk: '>=2.10.5 <3.0.0'

dependencies:
  angulardart: ^6.0.0
  angulardart_components: ^1.0.0
  angulardart_gallery:
    path: ../../angular_gallery
  angulardart_gallery_section:
    path: ../../angular_gallery_section
  build_config: '>=0.2.6 <0.5.0'
