/// Stub template for angulardart - native/AOT compatible.
///
/// AUTO-GENERATED by `ngdart generate-stubs` — DO NOT EDIT MANUALLY.
/// This file is a stub that allows AOT compilation on native platforms.
/// The actual template is generated by build_runner for web builds.
library;

void initReflector() {
  // No-op on native/AOT - reflection not needed for server rendering
}
