targets:
  $default:
    builders:
      angulardart_components|scss_builder:
        enabled: True
      angulardart_gallery|angulardart_gallery:
        enabled: False
      angulardart_gallery_section|angulardart_gallery_section:
        options:
          staticImageServer: "https://raw.githubusercontent.com"
